### PR TITLE
Add global counter

### PR DESCRIPTION
**Pull request by risbi0**
Global counter is saved in a Redis database, queried through an API. [source code](https://github.com/risbi0/kuru-kuru-count-api)
It is updated either 5 seconds since the last button click, or every 10 seconds if the tab is active or focused.

### CODE REVIEW

**Comment by duiqt** [comment]
thanks for helping out!

**Comment by duiqt** [comment]
there are some bug so i will revert it and try to find out

**Comment by risbi0** [comment]
What bugs did you find? I'll try to fix it.

**Comment by duiqt** [comment]
image
i think you can edit(?) the counter or so when pressing f12 and manually input the count number. After some refresh the page show like this.
image

or could be something else.

**Comment by duiqt** [comment]
if you need to see it live i'll push the code again and leave it there for sometime for you to check it out?

**Comment by risbi0** [comment]
No need

**Comment by risbi0** [comment]
I put some limits, and also separated the JavaScript in their on file. I'll go on and make a PR now.

**Pull request merged**
