### PR TITLE
Refactoring project

### PR DESCRIPTION
**Pull request by blacktunes**
Rewritten the page style and optimized some code according to my own ideas
There have been a lot of changes, and it doesn't matter to don't merge

Preview: https://herta-kuru-kappa.vercel.app/

### CODE REVIEW

**Comment by george-chou** [comment]
> Rewritten the page style and optimized some code according to my own ideas There have been a lot of changes, and it doesn't matter to don't merge
> 
> Preview: https://herta-kuru-kappa.vercel.app/

这个算大改。。。而且还把#72给囊括了。。。需要斟酌一下

**Comment by george-chou** [comment]
This is a big modification, please help review it. @fred913 @duiqt

**Comment by blacktunes** [comment]
> 这个算大改。。。而且还把#72给囊括了。。。需要斟酌一下

#72 想法挺好的，随机速度确实有趣
我刚才在手机上看发现确实会有声音结束动画才开始的问题，屏幕越窄越明显，需要再改改

改动确实很大，所以不合并也无所谓了
不过文字刷新和预加载的部分还是建议更一下，现在的代码每次按按钮会遍历所有i18n内容，预加载也有两套一样的代码实在不太妥

**Comment by fred913** [comment]
How about...
1. Pause the development in the `main` branch.
2. Create a new branch, and **rewrite the project from scratch**. I could do most of it myself *as it's my suggestion*.

**Comment by fred913** [comment]
Excellent notion! However, it necessitates further refinement. I shall endeavor to make progress based on the existing (modified) code until it reaches a state suitable for thorough evaluation.

**Pull request closed without merging**
