### PR TITLE
Add multi-language support

### PR DESCRIPTION
**Pull request by fred913**
according to issue #13 
I have added Chinese language support (text and voice files) and the experience is good (because I'm native Chinese).
Contributions for other languages are welcomed! It is easy to add them, just see inside `script.js`.

### CODE REVIEW

**Comment by duiqt** [comment]
i will look into it in abit after i get home. thanks for helping out!

**Comment by TororuInta** [comment]
> according to issue #13 I have added Chinese language support (text and voice files) and the experience is good (because I'm native Chinese). Contributions for other languages are welcomed! It is easy to add them, just see inside `script.js`.

I want to contribute for another language, should I do a new pull request?

**Comment by duiqt** [comment]
Either a pull request and we will look into it or you post thr code in js here so we can check out here and ađ it later.

**Comment by fred913** [comment]
@TororuInta Yes. The multi language data is stored in the js file. You
should create a PR to modify it.

**Pull request merged**
