### PR TITLE
Add Japanese support

### PR DESCRIPTION
**Pull request by fred913**
## Checklist
- [x] Texts
- [x] Audio
- [x] Ticket image

### CODE REVIEW

**Comment by duiqt** [comment]
yeah still need the card

**Comment by vgwik** [comment]
Japanese card.
card_jp

**Comment by fred913** [comment]
@vgwik TOO FAST! Thanks A LOT!!!

**Comment by duiqt** [comment]
nice!

**Comment by duiqt** [comment]
lemme know when you done @fred913 i will have to go soon

**Comment by fred913** [comment]
@duiqt Sure. btw, remember to check your inbox pls

**Comment by fred913** [comment]
and, here I don't have the Japanese audio files. Can anyone share them with me?

**Comment by duiqt** [comment]
@fred913 the jp audio is kuru one, en is "time to swirl"

**Comment by fred913** [comment]
wtf..I see

**Comment by duiqt** [comment]
well my original plan was just one kuru audio hence the "herta_kuru" name, you can just  copy the audio over jp, i will think about the herta en voice line later

**Pull request merged**
